esphome:
  name: relay-1

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

switch:
  - platform: gpio
    pin: GPIO23
    id: relay_switch
    name: "Smart Relay 1"
    restore_mode: ALWAYS_OFF
    inverted: true
